#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6001 #端口号
spring:
  profiles: dev # 开发环境
  applications:
    name: config-eureka-6001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6001 #端口号
spring:
  profiles: prod # 生产环境
  applications:
    name: config-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  server:
    enable-self-preservation: true # 开启自我保护机制*****************