#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: config-demo-provide
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/demo_project?serverTimezone=GMT%2B8&useSSL=false  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
  redis:
    host: redis.perf.ptcloud.t.home
    port: 6379
    max-wait: 30000 #连接池最大阻塞时间
    max-active: 100 #连接池最大连接和数量
    max-idle: 20 #连接池最大空闲连接
    min-idle: 0 #连接处最小连接数量
    timeout: 3000 #连接超时

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.pateo.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml       # mapper映射文件

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************


---