#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置

---
server:
  port: 8001 #端口号

spring:
  profiles: dev # 开发环境
  applications:
    name: demo-provide-8001
  datasource:
    url: jdbc:mysql://172.16.5.18:3309/test?serverTimezone=GMT%2B8&useSSL=false  # 数据库名称
    driver-class-name: com.mysql.cj.jdbc.Driver        # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    username: qingcloudbaic
    password: Qing%Baic
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl:
      defaultZone: http://172.25.25.40:6001/eureka/,http://172.25.25.40:6002/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

redis:
  host: 122.51.145.30
  port: 6379
  max-wait: 30000 #连接池最大阻塞时间
  max-active: 100 #连接池最大连接和数量
  max-idle : 20 #连接池最大空闲连接
  min-idle: 0 #连接处最小连接数量
  timeout: 3000 #连接超时
