#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 9527
spring:
  profiles: dev
  application:
    name: demo-project-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
management:
  endpoints:
    web:
      exposure:
        include: "*"
---