#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 9527
spring:
  profiles: dev
  application:
    name: demo-project-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: costomer_getlist_route
          uri: lb://PROJECT-DEMO-CONSUMER
          predicates:
            - Path=/consumer/product/list
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
management:
  endpoints:
    web:
      exposure:
        include: "*"
---