#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8092
spring:
  profiles: dev
  application:
    name: project-demo-consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
