#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8082
spring:
  profiles: dev
  application:
    name: project-weixin-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true


logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wxf713f388759c0a27 #（一个公众号的appid）
        secret: 0e0b22d935bfc44bf42c9480ed8adf7d（公众号的appsecret）
        token: weixin #（接口配置里的Token值）

mayikt:
  weixin:
    registration:
       code:
       ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="https://ke.qq.com/course/273548">腾讯课堂免费公开课</a>，欢迎观看97后架构师余老师的精品课程讲解。官方QQ群：<a href='https://jq.qq.com/?_wv=1027&k=5TVfAMF'>193086273</a>，期待你的加入，感谢！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!
