#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springbootv2zuul

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

zuul:
  routes:
    provider-consume:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /consumer/product/**
      serviceId: springbootv2zuulconsumer
      stripPrefix: false

    provider-user:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /consumer/redis/**
      serviceId: springbootv2zuulconsumer
      stripPrefix: false
